import type { PlanDefinition } from "./planTypes";

// ─── Plan catalogue ───────────────────────────────────────────────────────────

export const PLANS: PlanDefinition[] = [
  {
    id: "free",
    name: "Free",
    monthlyPrice: 0,
    annualPrice: 0,
    tagline: "Full terminal access. No card required.",
    accentColor: "text-zinc-300",
    accentBorder: "border-zinc-700/60",
    accentBg: "bg-zinc-900/30",
    ctaLabel: "Get started free",
    ctaHref: "/signup",
    features: [
      { label: "Live market pulse terminal",        included: true  },
      { label: "AI narratives + market cognition",  included: true  },
      { label: "Creator share card exports",        included: true  },
      { label: "Watchlists",                        included: true  },
      { label: "Market intelligence pages",         included: true  },
      { label: "Sport intelligence hubs (7)",       included: true  },
      { label: "News catalyst feed",                included: true  },
      { label: "Public terminal access",            included: true  },
      { label: "Creator distribution tools",        included: false },
      { label: "Partner analytics dashboard",       included: false },
      { label: "Branded exports",                   included: false },
      { label: "Structured API access",             included: false },
      { label: "AI feed endpoints",                 included: false },
    ],
  },
  {
    id: "partner",
    name: "Partner",
    monthlyPrice: 99,
    annualPrice: 79,
    tagline: "Creator distribution infrastructure.",
    accentColor: "text-amber-400",
    accentBorder: "border-amber-400/40",
    accentBg: "bg-amber-400/5",
    ctaLabel: "Upgrade to Partner",
    ctaHref: "/pricing#partner",
    recommended: true,
    features: [
      { label: "Everything in Free",                included: true  },
      { label: "Creator distribution network",      included: true  },
      { label: "Partner analytics dashboard",       included: true  },
      { label: "Broadcast infrastructure",          included: true  },
      { label: "Branded export tooling",            included: true  },
      { label: "Priority signal routing",           included: true  },
      { label: "Partner profile + reach metrics",   included: true  },
      { label: "Advanced volatility analytics",     included: true  },
      { label: "Export queue history",              included: true  },
      { label: "Creator performance analytics",     included: true  },
      { label: "Referral commissions",              included: true,  badge: "soon" },
      { label: "Telegram/X/Discord integrations",   included: true,  badge: "soon" },
      { label: "Structured API access",             included: false },
    ],
  },
  {
    id: "api",
    name: "API",
    monthlyPrice: 299,
    annualPrice: 239,
    tagline: "Structured data for intelligence systems.",
    accentColor: "text-blue-400",
    accentBorder: "border-blue-400/40",
    accentBg: "bg-blue-400/5",
    ctaLabel: "Unlock API Access",
    ctaHref: "/pricing#api",
    features: [
      { label: "Everything in Partner",             included: true  },
      { label: "Structured market intelligence API",included: true  },
      { label: "AI narrative endpoints",            included: true  },
      { label: "Odds + liquidity data feed",        included: true  },
      { label: "Provider integration layer",        included: true  },
      { label: "Higher refresh rate limits",        included: true  },
      { label: "Deep liquidity scan access",        included: true  },
      { label: "AI confidence history",             included: true  },
      { label: "WebSocket feed access",             included: true,  badge: "soon" },
      { label: "Enterprise API endpoints",          included: true,  badge: "soon" },
      { label: "Dedicated onboarding",              included: true,  badge: "soon" },
      { label: "SLA + uptime guarantee",            included: true,  badge: "soon" },
    ],
  },
];

export function getPlan(id: string): PlanDefinition | undefined {
  return PLANS.find((p) => p.id === id);
}
